apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  ### Just as a prevention, we do not want Argo CD to self delete
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: cluster-a
  project: default
  source:
    path: argocd
    repoURL: https://github.com/cnchit/argoproj-deployments
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ClientSideApplyMigration=false
    ### Disable Argo CD auto-sync to better control updates of what is merged upstream
    # automated:
    #   prune: true
    #   selfHeal: true
