apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-controlplane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: istio-controlplane
    repoURL: https://github.com/cnchit/argoproj-deployments
    targetRevision: HEAD
  destination:
    server: cluster-a
    namespace: istio-system
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
